"""
Static mapping of MRT/LRT station names (as returned by the API, uppercase)
to the transit line(s) they serve.

Line codes
----------
NSL  — North-South Line
EWL  — East-West Line
CCL  — Circle Line
DTL  — Downtown Line
NEL  — North-East Line
TEL  — Thomson-East Coast Line
BPL  — Bukit Panjang LRT
SLRT — Sengkang LRT
PLRT — Punggol LRT
"""

STATION_LINE_MAP: dict[str, list[str]] = {
    # ── North-South Line (NSL) ──────────────────────────────────────────────
    "JURONG EAST MRT STATION": ["NSL", "EWL"],
    "BUKIT BATOK MRT STATION": ["NSL"],
    "BUKIT GOMBAK MRT STATION": ["NSL"],
    "CHOA CHU KANG MRT STATION": ["NSL", "BPL"],
    "YEW TEE MRT STATION": ["NSL"],
    "KRANJI MRT STATION": ["NSL"],
    "MARSILING MRT STATION": ["NSL"],
    "WOODLANDS MRT STATION": ["NSL", "TEL"],
    "ADMIRALTY MRT STATION": ["NSL"],
    "SEMBAWANG MRT STATION": ["NSL"],
    "CANBERRA MRT STATION": ["NSL"],
    "YISHUN MRT STATION": ["NSL"],
    "KHATIB MRT STATION": ["NSL"],
    "YIO CHU KANG MRT STATION": ["NSL"],
    "ANG MO KIO MRT STATION": ["NSL"],
    "BISHAN MRT STATION": ["NSL", "CCL"],
    "BRADDELL MRT STATION": ["NSL"],
    "TOA PAYOH MRT STATION": ["NSL"],
    "NOVENA MRT STATION": ["NSL"],
    "NEWTON MRT STATION": ["NSL", "DTL"],
    "ORCHARD MRT STATION": ["NSL", "TEL"],
    "SOMERSET MRT STATION": ["NSL"],
    "DHOBY GHAUT MRT STATION": ["NSL", "NEL", "CCL"],
    "CITY HALL MRT STATION": ["NSL", "EWL"],
    "RAFFLES PLACE MRT STATION": ["NSL", "EWL"],
    "MARINA BAY MRT STATION": ["NSL", "CCL", "TEL"],
    "MARINA SOUTH PIER MRT STATION": ["NSL"],
    # ── East-West Line (EWL) ────────────────────────────────────────────────
    "PASIR RIS MRT STATION": ["EWL"],
    "TAMPINES MRT STATION": ["EWL", "DTL"],
    "SIMEI MRT STATION": ["EWL"],
    "TANAH MERAH MRT STATION": ["EWL"],
    "BEDOK MRT STATION": ["EWL"],
    "KEMBANGAN MRT STATION": ["EWL"],
    "EUNOS MRT STATION": ["EWL"],
    "PAYA LEBAR MRT STATION": ["EWL", "CCL"],
    "ALJUNIED MRT STATION": ["EWL"],
    "KALLANG MRT STATION": ["EWL"],
    "LAVENDER MRT STATION": ["EWL"],
    "BUGIS MRT STATION": ["EWL", "DTL"],
    "TANJONG PAGAR MRT STATION": ["EWL"],
    "OUTRAM PARK MRT STATION": ["EWL", "NEL", "TEL"],
    "TIONG BAHRU MRT STATION": ["EWL"],
    "REDHILL MRT STATION": ["EWL"],
    "QUEENSTOWN MRT STATION": ["EWL"],
    "COMMONWEALTH MRT STATION": ["EWL"],
    "BUONA VISTA MRT STATION": ["EWL", "CCL"],
    "DOVER MRT STATION": ["EWL"],
    "CLEMENTI MRT STATION": ["EWL"],
    "CHINESE GARDEN MRT STATION": ["EWL"],
    "LAKESIDE MRT STATION": ["EWL"],
    "BOON LAY MRT STATION": ["EWL"],
    "PIONEER MRT STATION": ["EWL"],
    "JOO KOON MRT STATION": ["EWL"],
    "GUL CIRCLE MRT STATION": ["EWL"],
    "TUAS CRESCENT MRT STATION": ["EWL"],
    "TUAS WEST ROAD MRT STATION": ["EWL"],
    "TUAS LINK MRT STATION": ["EWL"],
    "EXPO MRT STATION": ["EWL", "DTL"],
    "CHANGI AIRPORT MRT STATION": ["EWL"],
    # ── North-East Line (NEL) ───────────────────────────────────────────────
    "HARBOURFRONT MRT STATION": ["NEL", "CCL"],
    "CHINATOWN MRT STATION": ["NEL", "DTL"],
    "CLARKE QUAY MRT STATION": ["NEL"],
    "LITTLE INDIA MRT STATION": ["NEL", "DTL"],
    "FARRER PARK MRT STATION": ["NEL"],
    "BOON KENG MRT STATION": ["NEL"],
    "POTONG PASIR MRT STATION": ["NEL"],
    "WOODLEIGH MRT STATION": ["NEL"],
    "SERANGOON MRT STATION": ["NEL", "CCL"],
    "KOVAN MRT STATION": ["NEL"],
    "HOUGANG MRT STATION": ["NEL"],
    "BUANGKOK MRT STATION": ["NEL"],
    "SENGKANG MRT STATION": ["NEL", "SLRT"],
    "PUNGGOL MRT STATION": ["NEL", "PLRT"],
    # ── Circle Line (CCL) ───────────────────────────────────────────────────
    "BRAS BASAH MRT STATION": ["CCL"],
    "ESPLANADE MRT STATION": ["CCL"],
    "PROMENADE MRT STATION": ["CCL", "DTL"],
    "NICOLL HIGHWAY MRT STATION": ["CCL"],
    "STADIUM MRT STATION": ["CCL"],
    "MOUNTBATTEN MRT STATION": ["CCL"],
    "DAKOTA MRT STATION": ["CCL"],
    "MACPHERSON MRT STATION": ["CCL", "DTL"],
    "TAI SENG MRT STATION": ["CCL"],
    "BARTLEY MRT STATION": ["CCL"],
    "LORONG CHUAN MRT STATION": ["CCL"],
    "MARYMOUNT MRT STATION": ["CCL"],
    "CALDECOTT MRT STATION": ["CCL", "TEL"],
    "BOTANIC GARDENS MRT STATION": ["CCL", "DTL"],
    "FARRER ROAD MRT STATION": ["CCL"],
    "HOLLAND VILLAGE MRT STATION": ["CCL"],
    "ONE-NORTH MRT STATION": ["CCL"],
    "KENT RIDGE MRT STATION": ["CCL"],
    "HAW PAR VILLA MRT STATION": ["CCL"],
    "PASIR PANJANG MRT STATION": ["CCL"],
    "LABRADOR PARK MRT STATION": ["CCL"],
    "TELOK BLANGAH MRT STATION": ["CCL"],
    "BAYFRONT MRT STATION": ["CCL", "DTL"],
    # ── Downtown Line (DTL) ─────────────────────────────────────────────────
    "BUKIT PANJANG MRT STATION": ["DTL", "BPL"],
    "CASHEW MRT STATION": ["DTL"],
    "HILLVIEW MRT STATION": ["DTL"],
    "HUME MRT STATION": ["DTL"],
    "BEAUTY WORLD MRT STATION": ["DTL"],
    "KING ALBERT PARK MRT STATION": ["DTL"],
    "SIXTH AVENUE MRT STATION": ["DTL"],
    "TAN KAH KEE MRT STATION": ["DTL"],
    "STEVENS MRT STATION": ["DTL", "TEL"],
    "ROCHOR MRT STATION": ["DTL"],
    "DOWNTOWN MRT STATION": ["DTL"],
    "TELOK AYER MRT STATION": ["DTL"],
    "FORT CANNING MRT STATION": ["DTL"],
    "BENCOOLEN MRT STATION": ["DTL"],
    "JALAN BESAR MRT STATION": ["DTL"],
    "BENDEMEER MRT STATION": ["DTL"],
    "GEYLANG BAHRU MRT STATION": ["DTL"],
    "MATTAR MRT STATION": ["DTL"],
    "UBI MRT STATION": ["DTL"],
    "KAKI BUKIT MRT STATION": ["DTL"],
    "BEDOK NORTH MRT STATION": ["DTL"],
    "BEDOK RESERVOIR MRT STATION": ["DTL"],
    "TAMPINES WEST MRT STATION": ["DTL"],
    "TAMPINES EAST MRT STATION": ["DTL"],
    "UPPER CHANGI MRT STATION": ["DTL"],
    # ── Thomson-East Coast Line (TEL) ───────────────────────────────────────
    "WOODLANDS NORTH MRT STATION": ["TEL"],
    "WOODLANDS SOUTH MRT STATION": ["TEL"],
    "SPRINGLEAF MRT STATION": ["TEL"],
    "LENTOR MRT STATION": ["TEL"],
    "MAYFLOWER MRT STATION": ["TEL"],
    "BRIGHT HILL MRT STATION": ["TEL"],
    "UPPER THOMSON MRT STATION": ["TEL"],
    "MOUNT PLEASANT MRT STATION": ["TEL"],
    "NAPIER MRT STATION": ["TEL"],
    "ORCHARD BOULEVARD MRT STATION": ["TEL"],
    "GREAT WORLD MRT STATION": ["TEL"],
    "HAVELOCK MRT STATION": ["TEL"],
    "MAXWELL MRT STATION": ["TEL"],
    "SHENTON WAY MRT STATION": ["TEL"],
    "GARDENS BY THE BAY MRT STATION": ["TEL"],
    "FOUNDERS' MEMORIAL MRT STATION": ["TEL"],
    "TANJONG RHU MRT STATION": ["TEL"],
    "KATONG PARK MRT STATION": ["TEL"],
    "TANJONG KATONG MRT STATION": ["TEL"],
    "MARINE PARADE MRT STATION": ["TEL"],
    "MARINE TERRACE MRT STATION": ["TEL"],
    "SIGLAP MRT STATION": ["TEL"],
    "BAYSHORE MRT STATION": ["TEL"],
    "BEDOK SOUTH MRT STATION": ["TEL"],
    "SUNGEI BEDOK MRT STATION": ["TEL"],
    # ── Bukit Panjang LRT (BPL) ────────────────────────────────────────────
    "SOUTH VIEW LRT STATION": ["BPL"],
    "KEAT HONG LRT STATION": ["BPL"],
    "TECK WHYE LRT STATION": ["BPL"],
    "PHOENIX LRT STATION": ["BPL"],
    "PETIR LRT STATION": ["BPL"],
    "PENDING LRT STATION": ["BPL"],
    "BANGKIT LRT STATION": ["BPL"],
    "FAJAR LRT STATION": ["BPL"],
    "SEGAR LRT STATION": ["BPL"],
    "JELAPANG LRT STATION": ["BPL"],
    "SENJA LRT STATION": ["BPL"],
    "TEN MILE JUNCTION LRT STATION": ["BPL"],
    # ── Sengkang LRT (SLRT) ────────────────────────────────────────────────
    "COMPASSVALE LRT STATION": ["SLRT"],
    "RUMBIA LRT STATION": ["SLRT"],
    "BAKAU LRT STATION": ["SLRT"],
    "KANGKAR LRT STATION": ["SLRT"],
    "RANGGUNG LRT STATION": ["SLRT"],
    "CHENG LIM LRT STATION": ["SLRT"],
    "FARMWAY LRT STATION": ["SLRT"],
    "KUPANG LRT STATION": ["SLRT"],
    "THANGGAM LRT STATION": ["SLRT"],
    "FERNVALE LRT STATION": ["SLRT"],
    "LAYAR LRT STATION": ["SLRT"],
    "TONGKANG LRT STATION": ["SLRT"],
    "RENJONG LRT STATION": ["SLRT"],
    # ── Punggol LRT (PLRT) ─────────────────────────────────────────────────
    "COVE LRT STATION": ["PLRT"],
    "MERIDIAN LRT STATION": ["PLRT"],
    "CORAL EDGE LRT STATION": ["PLRT"],
    "RIVIERA LRT STATION": ["PLRT"],
    "KADALOOR LRT STATION": ["PLRT"],
    "OASIS LRT STATION": ["PLRT"],
    "DAMAI LRT STATION": ["PLRT"],
    "SAM KEE LRT STATION": ["PLRT"],
    "TECK LEE LRT STATION": ["PLRT"],
    "PUNGGOL POINT LRT STATION": ["PLRT"],
    "SAMUDERA LRT STATION": ["PLRT"],
    "NIBONG LRT STATION": ["PLRT"],
    "SUMANG LRT STATION": ["PLRT"],
    "SOO TECK LRT STATION": ["PLRT"],
}

# Full line name → line code mapping (accepts both code and full name in tools)
LINE_NAME_TO_CODE: dict[str, str] = {
    "NSL": "NSL",
    "NORTH-SOUTH LINE": "NSL",
    "NORTH SOUTH LINE": "NSL",
    "EWL": "EWL",
    "EAST-WEST LINE": "EWL",
    "EAST WEST LINE": "EWL",
    "NEL": "NEL",
    "NORTH-EAST LINE": "NEL",
    "NORTH EAST LINE": "NEL",
    "CCL": "CCL",
    "CIRCLE LINE": "CCL",
    "DTL": "DTL",
    "DOWNTOWN LINE": "DTL",
    "TEL": "TEL",
    "THOMSON-EAST COAST LINE": "TEL",
    "THOMSON EAST COAST LINE": "TEL",
    "BPL": "BPL",
    "BUKIT PANJANG LRT": "BPL",
    "BUKIT PANJANG": "BPL",
    "SLRT": "SLRT",
    "SENGKANG LRT": "SLRT",
    "PLRT": "PLRT",
    "PUNGGOL LRT": "PLRT",
}


def resolve_line_code(input_str: str) -> str | None:
    """
    Normalise a user-supplied line name or code to its canonical code.
    Returns None if no match is found.
    """
    normalised = input_str.strip().upper()
    return LINE_NAME_TO_CODE.get(normalised)


def get_stations_for_line(line_code: str) -> list[str]:
    """Return a list of station names (API format) that serve the given line code."""
    return [
        station for station, lines in STATION_LINE_MAP.items() if line_code in lines
    ]
